# fly.toml app configuration file
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "parody-app"
primary_region = "iad"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]

[env]
  PORT = "8000"
  PYTHONUNBUFFERED = "1"

[experimental]
  auto_rollback = true

[[services]]
  protocol = "tcp"
  internal_port = 8000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "get"
    path = "/health"
    protocol = "http"

[[mounts]]
  source = "parody_data"
  destination = "/app/data"

[processes]
  app = "bash /app/entrypoint.sh"